// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Song struct {
	ID           int     `json:"id"`
	SongName     string  `json:"songName"`
	SongDuration float64 `json:"songDuration"`
	SongHits     int     `json:"songHits"`
}

type SongInput struct {
	SongName     string  `json:"songName"`
	SongDuration float64 `json:"songDuration"`
	SongHits     int     `json:"songHits"`
}
